### ISSUE TITLE
Echo server panicked with ConnectionClosed error

### ISSUE THREAD

**Issue by Leo1003** [snapview/tokio-tungstenite#188] opened 2021-09-06 16:11 UTC
## Information
- Version: master (d566387)
- OS: Arch Linux
- Rust: 1.54.0

## Description

When I tried to run the echo server sample and using `websocat` to communicate with it.
The `accept_connection()` panicked with the `ConnectionClosed` error when the websocat reached EOF and closed the connection gracefully.

<details>
  <summary>Stack trace</summary>

```
thread 'tokio-runtime-worker' panicked at 'Failed to forward message: ConnectionClosed', examples/echo-server.rs:45:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::expect
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:997:23
   4: echo_server::accept_connection::{{closure}}
             at ./examples/echo-server.rs:45:5
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/future.rs:119:9
   7: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/core.rs:161:17
   8: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/loom/std/unsafe_cell.rs:14:9
   9: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/core.rs:151:13
  10: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:461:19
  11: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  12: std::panicking::try::do_call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  13: __rust_try
  14: std::panicking::try
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  15: std::panic::catch_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  16: tokio::runtime::task::harness::poll_future
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:449:18
  17: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:98:27
  18: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:53:15
  19: tokio::runtime::task::raw::poll
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/raw.rs:113:5
  20: tokio::runtime::task::raw::RawTask::poll
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/raw.rs:70:18
  21: tokio::runtime::task::LocalNotified<S>::run
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/mod.rs:343:9
  22: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:408:13
  23: tokio::coop::with_budget::{{closure}}
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:106:9
  24: std::thread::local::LocalKey<T>::try_with
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:400:16
  25: std::thread::local::LocalKey<T>::with
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:376:9
  26: tokio::coop::with_budget
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:99:5
  27: tokio::coop::budget
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:76:5
  28: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:407:9
  29: tokio::runtime::thread_pool::worker::Context::run
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:374:24
  30: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:359:17
  31: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/macros/scoped_tls.rs:61:9
  32: tokio::runtime::thread_pool::worker::run
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:356:5
  33: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:335:45
  34: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/blocking/task.rs:42:21
  35: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/core.rs:161:17
  36: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/loom/std/unsafe_cell.rs:14:9
  37: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/core.rs:151:13
  38: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:461:19
  39: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  40: std::panicking::try::do_call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  41: __rust_try
  42: std::panicking::try
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  43: std::panic::catch_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  44: tokio::runtime::task::harness::poll_future
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:449:18
  45: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:98:27
  46: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:53:15
  47: tokio::runtime::task::raw::poll
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/raw.rs:113:5
  48: tokio::runtime::task::raw::RawTask::poll
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/raw.rs:70:18
  49: tokio::runtime::task::UnownedTask<S>::run
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/mod.rs:379:9
  50: tokio::runtime::blocking::pool::Inner::run
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/blocking/pool.rs:265:17
  51: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/blocking/pool.rs:245:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

I think the error may occur at [src/compat.rs#L181](https://github.com/snapview/tokio-tungstenite/blob/d566387ed07b344bb0da9d6b361374acf3118d66/src/compat.rs#L181).

When the connection closed, the read end reach EOF and it try to flush the data before closing the write end. However, the whole connection is closed already. Therefore, `ConnectionClosed` error is returned.

I think this is not the expected behavior.

## Expected Behavior

The `Forward` future should complete successfully.
```rust
read.forward(write).await.expect("Failed to forward message")
```

## Note
This issue also exists on 0.13.0 (when using `warp` crate).

**Comment by application-developer-DA** [comment] 2021-09-07 19:15
Thanks for the report, quite interesting.

The thing is that the `Write` implementation is not something that `tokio` calls directly. The `Read` and `Write` requirements (as well as the whole `compat` layer) is there to be able to pass the stream to our "core" library (`tungstenite-rs`). So if your assumption is correct, someone (`tokio`) should have called `read_message()`, `write_message()` or `write_pending()` to cause the `ConnectionClosed` error. However, the `ConnectionClosed` error is only sent once from `tungstenite-rs` and it's used in `tokio-tungstenite` to determine when the `Stream` has reached the end, i.e. if you check the [`impl Stream`](https://github.com/snapview/tokio-tungstenite/blob/master/src/lib.rs#L278) you will notice that we convert the `ConnectionClosed` into the `None` (i.e. signalling the `tokio` that the `Stream` has just ended, after which no values will be read from the stream). Likewise we don't treat it as an error [for the `impl Sink`](https://github.com/snapview/tokio-tungstenite/blob/master/src/lib.rs#L318)'s `poll_close()`.

In theory the issue should not occur, because I believe that `forward` will merely read the messages from the `Stream` until it returns `None` and forwards them to the `Sink` when the message is received. Another thing is that we only return `ConnectionClosed` once. After that we return `AlreadyClosed`, so I'm really not sure what may cause this behavior. I'll probably need to dig into the implementation of `Forward` and compare it with what we currently have to see if we can fix it properly and if it's a bug. I really wonder how do we get the `ConnectionClosed` that turns into an error that the user sees (normally we just convert it inside `tokio-tungstenite` into `None` or `Ok(())` depending on whether we're talking about `Stream` or `Sink`).

**Comment by jxs** [comment] 2021-09-07 20:01
the panic also happens if you switch `forward` to:
```Rust
    while let Some(msg) = read.next().await {
        write.send(msg.unwrap()).await;
    }
```
I tried the example with `websocat` and the panic occurs cause there's a `Err(Protocol(ResetWithoutClosingHandshake))`  which I'd say it's probably cause `^C` makes `websocat` abruptly close the connection no?

**Comment by application-developer-DA** [comment] 2021-09-07 21:53
> I tried the example with websocat and the panic occurs cause there's a Err(Protocol(ResetWithoutClosingHandshake)) which I'd say it's probably cause ^C makes websocat abruptly close the connection no?

Ah, so **in your case** the panic is an expected behavior, because you read the `Result` from the stream, so whenever any abnormal close occurs, it will of course panic. The difference that I see is that in the stack trace that @Leo1003 posted, I see `ConnectionClosed`, not the `Protocol` error. However, @Leo1003 if you could re-check @jxs's example on your side and let us know which error you get, I think it would help us to understand if the cases are equal.

If you get the `Err(Protocol(ResetWithoutClosingHandshake))` like @jxs mentioned in his comment, then this behavior is expected and in fact correct. I.e. abnormal closure of the connection is an error and there is nothing we can do about it (if you code must be resilent to such errors, then it should just handle such things).

In our production code when such things happen we don't call `expect()` or `unwrap()` (that would be incorrect and inefficient), instead we handle errors and/or log the error. I would say ideally you should not call `expect()` on `forward()` or `socket.read()` in a real production code anyway (unless you're willing to handle panics etc).

**Comment by Leo1003** [comment] 2021-09-09 07:28
@application-developer-DA I tried @jxs 's codes with a little modifications:
```rust
// Codes omitted...

let (mut write, mut read) = ws_stream.split();
while let Some(msg) = read.next().await {
        write.send(msg.unwrap()).await.unwrap();
}
```

This produced the same error, it still panicked...
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionClosed', examples/echo-server.rs:46:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jxs** [comment] 2021-09-09 20:47
can you describe your steps to trigger the `ConnectionClosed` and `tungstenite` and `websocat`versions?

**Comment by Leo1003** [comment] 2021-09-10 02:05
I just run the run the server in the examples.

```bash
RUST_LOG=info cargo run --example echo-server
```

Then in another terminal, use websocat to send some texts.
```bash
echo "test" | websocat ws://127.0.0.1:8080
# Exits successfully
```

The worker thread of the server got the error and panicked.

---

The tungstenite version (`cargo tree | grep tungstenite`):
```
tokio-tungstenite v0.15.0 (/home/leo/sources/tokio-tungstenite)
└── tungstenite v0.15.0
```

Output of `websocat --version`:
```
websocat 1.8.0
```

**Comment by application-developer-DA** [comment] 2021-09-10 11:03
Ok, I think now I understand what's going on. So what must be happening in your case is the following:
1. You [successfully] receive a message from the WebSocket.
2. Then you start sending the message back.
3. At this point the other part closes the connection.

When you call `send()` the [`Send` future](https://docs.rs/futures-util/0.3.17/futures_util/sink/struct.Send.htmljj) is created. Whenever it's polled, it calls the [`poll_flush()` which in our case](https://github.com/snapview/tokio-tungstenite/blob/master/src/lib.rs#L311) resolves to calling to [`write_pending()`](https://github.com/snapview/tungstenite-rs/blob/master/src/protocol/mod.rs#L366). The connection is getting closed while we're flushing the message. In other words, you must have received a close frame while reading the message and then tried to send it back, so the `write_pending()` returned the `ConnectionClosed`. We can't "fix" it on `tungstenite-rs` side, because it would not allow the user to differentiate between "message is sent" and "message is not sent, because connection has just been closed". We could change the `tokio-tungstenite`'s implementation for the `poll_flush()` to ignore the `ConnectionClosed`, but then we get the similar problem: if you call `send()` and the future succeeds without an error, does it mean that the message has been sent or does it mean that message probably has not been sent due to the error? ;) Currently if the future completes without the error you know that it was sent. If we change this logic, the 2 cases become indistinguishable. So I don't think there is something we can fix in this case.

I think the difference between your case and what @jxs is that in @jxs's case the connection went closed without getting the close frame from the other side, which resulted in the `ProtocolError`. In your case the code did receive the close frame, so it was a normal `ConnectionClose`. Could you use `dbg!()` on the message that you get from the client before sending it back? There must be a `Close` message there.

**Comment by Leo1003** [comment] 2021-09-10 16:21
Yes, you are right, there is a close message exactly. Thanks for pointing it out, I know why it happened now. The codes send the close message after the socket has been closed...

```
[2021-09-10T16:10:58Z INFO  echo_server] Listening on: 127.0.0.1:8080
[2021-09-10T16:11:00Z INFO  echo_server] Peer address: 127.0.0.1:49794
[2021-09-10T16:11:00Z INFO  echo_server] New WebSocket connection: 127.0.0.1:49794
[examples/echo-server.rs:46] &msg = Ok(
    Text(
        "test\n",
    ),
)
[examples/echo-server.rs:46] &msg = Ok(
    Close(
        None,
    ),
)
thread 'tokio-runtime-worker' panicked at 'Failed to send messages: ConnectionClosed', examples/echo-server.rs:47:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by application-developer-DA** [comment] 2021-09-10 18:29
Ok, great! Then the mystery is solved :)

In the real code you may want to `match` the message and only handle the messages that are "real" messages, e.g. the binary or text messages with the data that you sent, ignoring pings and pongs and doing any sort of resource release (if any) when close frame is received.

Since the original problem seem to have been solved I'm going to close the issue. Feel free to amend or re-open it if something looks wrong ;)

**Closed by application-developer-DA** 2021-09-10 18:29 UTC
Labels: question

**Comment by Leo1003** [comment] 2021-09-10 19:55
I will make a PR to fix the example to prevent people being misled.
