### ISSUE TITLE
Cannot pass WebSocketStream as return value, due to hidden AutoStream type

### ISSUE THREAD

**Issue by runapp** [snapview/tokio-tungstenite#151] opened 2021-02-14 16:38 UTC
Hi, I've found that it's hard to return an `WebSocketStream` from a function, cause it's type is hard to write down. Is this on purpose? If so, any suggestions on achieving similar goal?

**Comment by strohel** [comment] 2021-02-15 18:01
I would have to investigate more to actually answer your question, but note that @dnaka91 is touching these types in https://github.com/snapview/tokio-tungstenite/pull/147/files

**Comment by application-developer-DA** [comment] 2021-02-26 14:01
Did I get the problem right: the issue is that you just don't like the long type of `WebSocketStream<lots of stuff>` and would like to use the `AutoStream` alias instead?

I'm asking, because I don't think that you "cannot pass WebSocketStream as return value" due to the fact that if the type were hidden [while having other public function that returns it] `tokio-tungstenite` would not compile with the `can't leak private type` error (E0446). Which makes me assume that is it possible to use `WebSocketStream`, it's just a bit cumbersome to write the full type as `WebSocketStream<MaybeTlsStream<..>>`, so you would prefer writing a bit shorter version `WebSocketStream<AutoStream<...>>`? (`AutoStream` is [just an alias](https://github.com/snapview/tokio-tungstenite/blob/master/src/connect.rs#L30))

> If so, any suggestions on achieving similar goal?

Depends on what you're trying to achieve, e.g. if you turn it into a stream of messages that you handle, you could write return `impl Stream<Item = Message>` instead of `WebSocketStream<a bunch of stuff here>`.

**Comment by runapp** [comment] 2021-02-26 21:56
@application-developer-DA
No and yes.
In fact I have `type TSWebsocketStream = WebSocketStream<MaybeTlsStream<TcpStream>>;` now in my code. I do think the original type is too long, but further more I think it's not safe to have that type of typedef in my own code, which relies on the inner detail of this crate. To my thought, if a type is private, it might change in any commit. `AutoStream` is just the hidden type which brings the concern to me.
Using trait is a good idea, and more "rustly" I think. And it seems that most place passing an `T:Stream+Sink` would be enough. But exposing each type in `WebSocketStream<AutoStream<TcpStream>>` or creating a new public type alias for it would still be great, cause `connect_async` only returns that specific type.

**Comment by application-developer-DA** [comment] 2021-02-26 22:12
Ok, then I think it's akin to https://github.com/snapview/tungstenite-rs/issues/181#issuecomment-786851749, i.e. we could make it public, perhaps we've just forgotten to make `AutoStream` public for `tokio-tungstenite`.

**Comment by runapp** [comment] 2021-02-26 22:16
That sounds reasonable. Making `AutoStream` public is just what I want. I should have written it in the initial issue description.

**Comment by strohel** [comment] 2021-03-01 11:44
Note that https://github.com/snapview/tokio-tungstenite/pull/147/files currently removes `AutoStream` completely, so this may be resolved as a side-effect of it.

**Comment by runapp** [comment] 2021-03-02 18:14
I do have seen it, but application-developer-DA was so kind that I feel like I must explain :)
Anyway whether `AutoStream` is removed or exported, the returned type of `connect_async` will be stable in next release. For now it's enough to use `WebSocketStream<MaybeTlsStream<TcpStream>>`. I was just fearing that one day it(`MaybeTlsStream`) silently changed and I lost my mind when coming back to my code.

**Comment by application-developer-DA** [comment] 2021-08-09 13:28
Alright folks, let me close this issue as we don't have the `AutoStream` type anymore and so I think the issue may confuse others ;) Let's better open a new one once (if) we encounter something similar in the new version (which ideally should not have this issue anymore).

**Closed by application-developer-DA** 2021-08-09 13:28 UTC
Labels: question
