### ISSUE TITLE
no output when running examples/client.rs

### ISSUE THREAD

**Issue by bbigras** [snapview/tokio-tungstenite#3] opened 2017-03-28 17:09 UTC
When I try https://github.com/snapview/tungstenite-rs/blob/master/examples/client.rs, I got data from the server but not when I try https://github.com/snapview/tokio-tungstenite/blob/master/examples/client.rs using the same URL.

I don't see anything after the handshake.

```
addr: V4(127.0.0.1:3012)
WebSocket handshake has been successfully completed
```

Linux x86_64
rustc 1.17.0-nightly (7846dbe0c 2017-03-26)
tokio-tungstenite 0.1.0
tungstenite 0.1.1

**Comment by application-developer-DA** [comment] 2017-03-28 17:22
Hi @bbigras , do you use the server from the `tokio-tungstenite` examples? Or is it a different one?

**Comment by bbigras** [comment] 2017-03-28 17:25
I use the `ws` crate.

**Comment by application-developer-DA** [comment] 2017-03-28 17:33
This one: https://github.com/housleyjk/ws-rs/blob/master/examples/server.rs ?

I've just checked the client with it and it works. Have you tried to type something in the terminal and press "Enter" after you started `tokio-tungstenite` client example? The client does not send anything to the server after the handshake is completed, it forwards the data read on stdin to the server (the client from `tungstenite-rs` sends a "Hello WebSocket" on start).

**Comment by bbigras** [comment] 2017-03-28 17:41
In my case my server doesn't expect any data from the client. The data only goes from the server to the client. It's a pubsub service.

> Have you tried to type something in the terminal and press "Enter" after you started tokio-tungstenite client example?

I just tried and it didn't do anything on the client side. The client still doesn't seem to 
receive data from the server.

I'll try to reproduce with a small server.

**Comment by bbigras** [comment] 2017-03-28 18:27
One weird thing is that if I kill the server. The client prints the data to stdout.

**Comment by bbigras** [comment] 2017-03-28 18:43
I get some data if I send a lot of it.

Could it be possible that stdout is never flushed?

**Comment by bbigras** [comment] 2017-03-28 18:49
It works with `stdout.flush().unwrap();`.

**Comment by application-developer-DA** [comment] 2017-03-29 08:20
Ok, cool, seems that it had something to do stdout and flusing.

`tokio-tungstenite` itself does not do any fancy things, we just rely on `tokio` defined traits and use methods from `tungstenite-rs`. I'll close the issue for now (seems that the problem is solved, right?).

If you encounter any problems here again, feel free to open a new one with a test case illustrating the incorrect behavior. Thanks!

**Closed by application-developer-DA** 2017-03-29 08:20 UTC

**Comment by bbigras** [comment] 2017-03-29 13:41
> seems that the problem is solved, right?

Yes but it could be a good idea to flush stdout in `examples/client.rs` so the next guy doesn't waste his and your time again.

**Comment by application-developer-DA** [comment] 2017-03-29 13:55
Perhaps, I have to think about it. The point here is that examples were all based on `tokio-core` examples, so the client part is basically a `connect` example from `tokio-core` (https://github.com/tokio-rs/tokio-core/blob/master/examples/connect.rs), so the examples here are symmetrical to `tokio-core`.
