### ISSUE TITLE
The current release of tokio-tungstenite does not build with the current tungstenite

### ISSUE THREAD

**Issue by lu-zero** [snapview/tokio-tungstenite#246] opened 2022-11-28 14:41 UTC
And also the current master branch:
```
❯ cargo check
    Checking tungstenite v0.17.3
error[E0432]: unresolved import `sha1`
  --> /Users/lu_zero/.cargo/registry/src/github.com-1ecc6299db9ec823/tungstenite-0.17.3/src/handshake/mod.rs:15:5
   |
15 | use sha1::{Digest, Sha1};
   |     ^^^^ use of undeclared crate or module `sha1`
   |
help: there is a crate or module with a similar name
   |
15 | use sha_1::{Digest, Sha1};
   |     ~~~~~
```

**Comment by lu-zero** [comment] 2022-11-28 14:44
Using tungstenite master make it work:
``` diff
diff --git a/Cargo.toml b/Cargo.toml
index cfb78b8..31b3bd8 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -26,17 +26,18 @@ __rustls-tls = ["rustls", "tokio-rustls", "stream", "tungstenite/__rustls-tls",
 stream = []

 [dependencies]
 log = "0.4"
 futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
 tokio = { version = "1.0.0", default-features = false, features = ["io-util"] }

 [dependencies.tungstenite]
-version = "0.17.3"
+git = "https://github.com/snapview/tungstenite-rs"
+features = ["handshake"]
 default-features = false

 [dependencies.native-tls-crate]
 optional = true
 package = "native-tls"
 version = "0.2.7"

 [dependencies.rustls]

```

**Comment by sdroege** [comment] 2022-11-28 14:47
The problem here is that *tungstenite* does not build without that feature. tokio-tungstenite may or may not be fine without that feature after that is fixed.

If tokio-tungstenite needs the feature now then this would be a breaking change in tungstenite and should be reverted, and then re-added in the 0.18 release.

**Comment by Icelk** [comment] 2022-11-28 15:26
I think the plan here was to merge the fix after a new version of tungstenite was released: #240

This and tungstenite should anyway be updated together. Regarding the breaking change: if this is released in 0.18, then it's fine according to Rust's semver. Have I missed anything?

**Comment by sdroege** [comment] 2022-11-28 15:44
It was released as part of 0.17.3. That's the problem :) 0.18 would've been fine

**Comment by Icelk** [comment] 2022-11-28 15:56
I see. Could we fix the problem temporary here by releasing another patch version of tokio-tungstenite which requires the feature, then make the flag optional in 0.18 of this crate? Or release 0.18.4 of tungstenite without the feature and yank 0.18.3? That would be the only way to keep both crates from failing semver. As a counterargument: how many use tungstenite directly? Updating this crate should fix the issues for most users.

**Comment by sdroege** [comment] 2022-11-28 16:09
Actually... there was no tungstenite update. The problem is that `sha-1` had breaking changes (it changed the crate name). The broken version is yanked now.

Sorry for the noise.

**Comment by Icelk** [comment] 2022-11-28 17:11
Right, so we need to push 0.18 (or a patch without the handshake PR) ASAP?

**Comment by sdroege** [comment] 2022-11-28 17:19
No, I don't think anything needs doing

**Comment by lu-zero** [comment] 2022-11-28 18:34
thank you for digging down to the sha1 crate :)

**Comment by lu-zero** [comment] 2022-11-28 18:35
In any case going with 0.18 for both tokio-tungstenite and tungstenite with the introduction of the `handshake` feature would be good :)

**Comment by daniel-abramov** [comment] 2022-11-28 22:12
Ok, `tungstenite` released, now waiting for the small change in https://github.com/snapview/tokio-tungstenite/pull/240#pullrequestreview-1196622857 so that we can merge it and release a new version of `tokio-tungstenite`.

**Comment by daniel-abramov** [comment] 2022-11-28 22:15
I think this issue can be closed now, right? I'm gonna close it now then and then wait for https://github.com/snapview/tokio-tungstenite/pull/240 to be completed, then I'll be able to release a new version of `tokio-tungstenite`.

**Closed by daniel-abramov** 2022-11-28 22:15 UTC
