### ISSUE TITLE
Support tokio 0.2 and futures 0.3

### ISSUE THREAD

**Issue by paulzhang5511** [snapview/tokio-tungstenite#64] opened 2019-08-13 00:42 UTC
The tokio 0.2.0-alpha and is released. 

[futures 0.3](https://crates.io/crates/futures)

[tokio 0.2](https://crates.io/crates/tokio)

**Comment by application-developer-DA** [comment] 2019-08-13 07:08
We're glad to do so as soon as it gets stable. Currently it's in alpha stage and I believe if we start adapting `tokio-tungstenite` to it, we'll have to make updates each time they change the corresponding crates (as it's still `alpha`, I expect that some changes might happen which will force us to make the corresponding changes in `tokio-tungstenite`).

**Comment by vorot93** [comment] 2019-08-15 11:05
They don't change that much anymore, really. And when they do it's usually a simple matter of search and replace.

**Comment by Drevoed** [comment] 2019-08-29 17:25
I am currently in progress of migrating tokio-tungstenite to futures 0.3 and tokio 0.2. So far everything seems good except one thing. Seeing as tokio-io 0.1 traits `AsyncRead` and `AsyncWrite` inherited from `Read` and `Write` respectively, current implementation was fine. However, futures 0.3 `AsyncRead` and `AsyncWrite` *do not* inherit `std::io` traits, which is a pretty big problem, seeing as tungstenite types and functions take types which have traits bound as `Read` or `Write`.

I am not sure about an optimal fix, though, if you have any ideas - please tell them.

**Comment by application-developer-DA** [comment] 2019-09-03 20:43
Good question. I have to think how to deal with that properly. The documentation for new `AsyncRead` and `AsyncWrite` still reflects the old state (it asserts that both are inherited from `Read` and `Write`, which apparently is not true).

There is a similar issue about that in tokio: https://github.com/tokio-rs/tokio/issues/1482

I have to check how this problem was solved for other crates which had similar issues. So far it looks like there are only some [temporary] kludges which others do to have some sort of a compatibility layer.

**Comment by agalakhov** [comment] 2019-09-03 21:18
It may be solved by introducing `NonBlockingRead` trait including exactly the same methods as `Read` but always non-blocking. Any `Read` or `AsyncRead` can then be turned into `NonBlockingRead`.

**Comment by application-developer-DA** [comment] 2019-09-03 21:28
If we implement template requirements in `tungstenite-rs` which rely on `NonBlockingRead` and `NonBlockingWrite`, it may be counter-intuitive, that you can pass any `Read + Write` stream there (`tungstenite-rs` can work with both blocking and non-blocking streams).

I think it may make sense to check how `tokio` maintainers solved the same problem in `native-tls` which has a similar semantics at this place. The did solve the problem, but it's rather a kludge (https://github.com/tokio-rs/tokio/blob/master/tokio-tls/src/lib.rs#L37), which [also was mentioned by Carl](https://github.com/tokio-rs/tokio/issues/1482#issuecomment-525026081).

**Comment by najamelan** [comment] 2019-09-04 15:31
I feel one way to solve this is to create a custom type in tokio-tungstenite that is generic over AsyncRead/AsyncWrite, and that implements Read/Write and pass that to tungstenite. In that case no changes need to be made outside of tokio-tungstenite.

Note that there are some extra issues, currently there are 2 different implementations of AsyncRead/AsyncWrite, in tokio and in the futures library. That's unfortunate. I haven't really understood what the problem is with futures version.

Both implementations take a `&[u8]` in `poll_write` though. I don't really see how we can make zero copy networking code with that. I would hope that we could take a `Bytes` from the bytes crate, and then have that in a websocket message rather than a `Vec<u8>` (as it doesn't seem Bytes has a zero cost conversion into Vec).

As an example why, I'm implementing AsyncRead/AsyncWrite on top of websockets, in order to allow libraries that work over that to work also from a browser in wasm. Currently in AsyncWrite I have to make an extra copy to create a websocket message. It would be nice if we had an ecosystem wide solution for compatible interfaces everywhere that do not require making unnecessary copies.

If there would be motivation, a cool addition to tokio-tungstenite would be if it implemented AsyncRead/AsyncWrite for WebSocketStream instead of needing an external library for that.

**Comment by paulzhang5511** [comment] 2019-11-13 01:14
The future 0.31 is released.

**Comment by FreeFull** [comment] 2019-11-14 21:56
Perhaps WebSocketStream should implement `Stream` with `Item = Result`, instead of implementing TryStream. TryStream is automatically implemented for `Stream`s of `Result`s, so this would be strictly more flexible. For example, right now you can't use the `split` method from `StreamExt` (there is no equivalent for `TryStream`)

**Comment by kellytk** [comment] 2019-11-27 10:45
[Tokio 0.2](https://github.com/tokio-rs/tokio/releases/tag/tokio-0.2.1) has been released.

**Comment by kellytk** [comment] 2020-01-08 03:38
https://github.com/snapview/tokio-tungstenite/pull/68 is merged.

**Comment by application-developer-DA** [comment] 2020-01-08 08:45
Alright, seems like we can close this issue now. We just need to publish the new version to crates.io.

**Comment by kellytk** [comment] 2020-01-11 19:17
@application-developer-DA What work remains to publish the new version?

**Comment by agalakhov** [comment] 2020-01-11 21:11
Fixing error handling in Tungstenite. There are some issues with autobahn test after recent changes.

**Comment by dovahcrow** [comment] 2020-01-15 00:29
Could it be possible to first release an alpha version, a.k.a. `0.10.0-alpha.1` to allow downstream libs to publish?

**Comment by Redrield** [comment] 2020-01-16 04:13
I can't publish [nt-rs](https://github.com/first-rust-competition/nt-rs) with async/await until this is on crates because of the websockets features. An alpha release would be nice.

**Comment by dmarcuse** [comment] 2020-01-30 15:10
Any update on this?

**Comment by agalakhov** [comment] 2020-01-31 02:35
Version 0.10.0 released today with Tokio 0.2 support.

**Closed by agalakhov** 2020-01-31 02:35 UTC
Labels: enhancement
